chore: jdbc.next & honeySql2
leihs/leihs-my pull request #5
Opened 2023-11-15 16:06 UTC by SeduroDotCom

2023-11-16 10:29 UTC, SeduroDotCom commented on src/leihs/my/password_restore/back.clj
> +    (jdbc/execute-one! tx (spy query))))
Wurde direkt in my implementiert anstatt die Version von shared-clj (java.jdbc) zu verwenden:
1. https://github.com/leihs/leihs-clj-shared/blob/a5a91b47a4aa3dc1ec134d72dcb79cb035c1fd22/src/leihs/core/sign_in/back.clj#L16
2. https://github.com/leihs/leihs-clj-shared/blob/a5a91b47a4aa3dc1ec134d72dcb79cb035c1fd22/src/leihs/core/sign_in/shared.clj#L45

TODO
- Renaming: user-with-unique-id-new -> user-with-unique-id

2023-11-16 10:42 UTC, SeduroDotCom commented on src/leihs/my/user/shared.clj
> +     (:crypt result))))
FYI: shared-clj version (java.jdbc)
1. https://github.com/leihs/leihs-clj-shared/blob/master/src/leihs/core/auth/shared.clj#L18-L28

2023-11-16 14:24 UTC, nimaai requested changes
maybe i missed to comment some lines but you get the idea 🙏

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/back/html.clj
> +        query (sql-format {:select [:*] :from [:users] :where [:= :id [:cast user-id :uuid]]})]
prefer the honeysql functions representation anyway, otherwise each keyword on a newline.

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/initial_admin/back.clj
> +                           :where [:= :is_admin true]})
prefer the honeysql functions representation anyway, otherwise each keyword on a newline.

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/initial_admin/back.clj
> +                     (h/returning :*))
use `sql` namespace alias instead of `h`

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/initial_admin/back.clj
> +        insert-sql (sql-format insert-sql)]
avoid duplicate temp variables in `let` construct

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/initial_admin/back.clj
> +                                 :values [[(:id user)]]})]
prefer the honeysql functions representation anyway

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/language.clj
> +    (set-language-cookie (jdbc/execute-one! tx (sql-format {:select [:*] :from [:languages] :where [:= :locale locale]})))))
prefer the honeysql functions representation anyway, otherwise each keyword on a newline.

and `->>` ;-)

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +  (-> (h/insert-into :emails)
use `sql` namespace alias instead of `h`

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +             }
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +  (let [sql {:select :* :from :user_password_resets :where [:= (normalize-token-str token-param) :user_password_resets/token]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +                                             ]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +        p (println ">>>user " user)
avoid duplicate temp variables in `let` construct

`debug` instead of `println` or remove

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +              [:= :user_password_resets.token (normalize-token-str token)]])
use `sql` namespace alias instead of `h`

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +                           auth-page)}))
indent properly

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +                     (h/returning :*))
use `sql` namespace alias instead of `h`

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +   (let [sql {:select [[[:crypt password [[[:gen_salt "bf"]]]]]]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +   (when (let [s {:select [[[:count :*]]] :from :api_tokens :where [:and [:= :user_id [:cast user-id :uuid]] [:= :id [:cast api-token-id :uuid]]]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +           data (dissoc data :id :created_at)
avoid duplicate temp variables in `let` construct

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +  (let [sql {:select api-token-selects :from :api-tokens :where [:and [:= :user_id [:cast user-id :uuid]] [:= :id [:cast api-token-id :uuid]]]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +  (let [sql {:delete-from :api-tokens :where [:and [:= :user_id [:cast user-id :uuid]] [:= :id [:cast api-token-id :uuid]]]}
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/api_tokens/back.clj
> +      (h/order-by [:created_at :desc])
use `sql` namespace alias instead of `h`

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/shared.clj
> +                   :returning [:*]})))
prefer the honeysql functions representation

2023-11-16 14:24 UTC, nimaai commented on src/leihs/my/user/shared.clj
> +   (let [sql {:select [[[:crypt password [[[:gen_salt "bf"]]]]]]}
prefer the honeysql functions representation

2023-11-20 14:36 UTC, nimaai requested changes
great. just few small things more

2023-11-20 14:36 UTC, nimaai commented on src/leihs/my/password_restore/back.clj
> +                  [:= [[[:lower :users/email]]] [:lower (-> user-unique-id (or ""))]]])
`[:lower :users/email]` should be enough

2023-11-20 14:36 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
> +   (-> (sql/select [[[:crypt password [[:gen_salt "bf"]]]] :pw_hash])
`[[:crypt password [:gen_salt "bf"]] :pw_hash]` should be enough

2023-11-20 14:36 UTC, nimaai commented on src/leihs/my/user/api_token/back.clj
>  (defn patch
my proposal for better readiblity:
```clj
(defn patch
  ([{tx :tx-next data :body {user-id :user-id
                             api-token-id :api-token-id} :route-params}]
   (patch api-token-id user-id data tx))
  ([api-token-id user-id data tx]
   (let [user-token-condition [:and [:= :user_id [:cast user-id :uuid]] 
                               [:= :id [:cast api-token-id :uuid]]]]
     (when (-> (sql/select :*)
               (sql/from :api_tokens)
               (sql/where user-token-condition)
               sql-format
               (->> (jdbc/execute-one! tx)))
       (let [revised-data (-> data
                              (normalize-create-or-update-params)
                              (dissoc :id :created_at))]
         (-> (sql/update :api_tokens)
             (sql/set revised-data)
             (sql/where user-token-condition)
             sql-format
             (->> (jdbc/execute-one! tx))))
       {:status 204}))))
```

2023-11-20 14:36 UTC, nimaai commented on src/leihs/my/user/shared.clj
> +   (-> (sql/select [[[:crypt password [[:gen_salt "bf"]]]] :pw_hash])
`[[:crypt password [:gen_salt "bf"]] :pw_hash]` should be enough

2023-11-20 16:41 UTC, nimaai approved these changes
👍

2023-11-20 17:00 UTC, merged